# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Jiawei Gao
tagline:          Jiawei Gao's Homepage
description:      
url:              http://jiaweigao.com
baseurl:          /

author:
  name:           'Jiawei Gao'

paginate:         5
