# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Jiawei Gao
description:      
url:              http://jiaweigao.com
baseurl:          /

author:
  name:           'Jiawei Gao'

paginate:         5
